image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 14.0.2.j9-adpt
    command: 'echo "TODO: Replace with command to start project"'

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080